### ISSUE TITLE
Issues with `gcrotmk` docstring

### ISSUE THREAD

**Issue by rgommers** [anushkasuyal/scipy#1]
This may be a good getting started issue. The `gcrotmk` documentation (http://scipy.github.io/devdocs/reference/generated/scipy.sparse.linalg.gcrotmk.html) has a number of little issues that could be addressed:
- the `LinearOperator` mention in the parameter description of `A` should be a link
- the References and Examples sections are the wrong way around (see the `numpydoc` guidelines)
- there are several issues where code objects are not typeset as code (e.g., `A` in the parameter description for `M`, and `callback(xk)` in the description of `callback`)
- The `maxiter` parameter is missing the description of what the default value is.

**Comment by anushkasuyal** [comment]
- resolved the typesetting errors - as per numpydoc standard, all the parameter/argument names are to be enclosed in single backticks so I corrected them throughout the file.

- resolved the maxiter missing parameter description issue.

First PR has been merged into SciPy.

**Comment by rgommers** [comment]
Ah I see it at https://github.com/scipy/scipy/pull/21094. Nice!

A couple of small workflow tips:
- the `[docs only]` doesn't have to be on the first line of the commit message; better to put it at the end (if the whole message is one line, then use: one-line summary, then blank line, then `[docs only]`)
- If you want to apply suggested changes through the GitHub UI, it's better to look at the diff view and use the option to batch-apply them all at once (you can't do this from the https://github.com/scipy/scipy/pull/21094 view, only from https://github.com/scipy/scipy/pull/21094/files).

**Comment by anushkasuyal** [comment]
resolved the wrong ordering of sections, and the missing cross-link for `LinearOperator` in docs. #21096

**Comment by rgommers** [comment]
Nice work! First win on the board:)
